#!/usr/bin/env bash

URL=$1

wget --mirror \
  --no-parent \
  --convert-links \
  --adjust-extension \
  --page-requisites \
  -e robots=off \
  -U 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0' \
  $URL
